netflixapp/urls.py
from django.urls import path
from .views import Home, ProfileList, ProfileCreate, MovieList, MovieDetail, PlayMovie

app_name = 'netflixapp'

urlpatterns = [
    path('', Home.as_view(), name="Home"),
    path('profiles/', ProfileList.as_view(), name="profile-list"),
    path('profiles/create/', ProfileCreate.as_view(), name="profile-create"),
    path('watch/<str:profile_id>/', MovieList.as_view(), name="movie-list"),
    path('watch/detail/<str:movie_id>/', MovieDetail.as_view(), name="movie-detail"),
    path('watch/play/<str:movie_id>/', PlayMovie.as_view(), name="play-movie"),
      
    #path('movies/',movies.as_view(),name='movies'),
    #path('new_&_popular/',new_pop.as_view(),name='new_pop'),

]

netflixapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

AGE_CHOICES = (
    ('All', 'All'),
    ('Kids', 'Kids'),
)

MOVIE_CHOICES = (
    ('seasonal', 'Seasonal'),
    ('single', 'Single'),
)

class CustomUser(AbstractUser):
    profiles = models.ManyToManyField('Profile', blank=True)

class Profile(models.Model):
    name = models.CharField(max_length=1000)
    age_limit = models.CharField(choices=AGE_CHOICES, max_length=10)
    uuid = models.UUIDField(default=uuid.uuid4)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=1000)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(default=uuid.uuid4)
    type = models.CharField(choices=MOVIE_CHOICES, max_length=10)
    video = models.ManyToManyField('Video')
    image = models.ImageField(upload_to='covers')
    age_limit = models.CharField(choices=AGE_CHOICES, max_length=10)

    def __str__(self):
        return self.title

class Video(models.Model):
    title = models.CharField(max_length=1000)
    file = models.FileField(upload_to='movies')

    def __str__(self):
        return self.title

netflixapp/forms.py
from django.forms import ModelForm
from netflixapp.models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['uuid']

netflixapp/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from . forms import ProfileForm
from . models import Profile, Movie



class Home(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('netflixapp:profile-list')
        return render(request, 'index.html')

method_decorator(login_required, name='dispatch')
class ProfileList(View):
    def get(self, request, *args, **kwargs):
        
        profiles = request.user.profiles.all()

        context = {
            'profiles':profiles
        }
        return render(request, 'profilelist.html', context)

method_decorator(login_required, name='dispatch')
class ProfileCreate(View):
    def get(self, request, *args, **kwargs):
        form = ProfileForm()
        context = {
            'form':form
        }
        return render(request, 'profilecreate.html', context)

    def post(self, request, *args, **kwargs):
        form = ProfileForm(request.POST or None)
        if form.is_valid():
            profile = Profile.objects.create(**form.cleaned_data)
            if profile:
                request.user.profiles.add(profile)
                return redirect('netflixapp:profile-list')
        context = {
            'form':form
        }
        return render(request, 'profilecreate.html', context)

method_decorator(login_required, name='dispatch')
class MovieList(View):
    def get(self, request, profile_id, *args, **kwargs):
        try:
            profile = Profile.objects.get(uuid=profile_id)
            movies = Movie.objects.filter(age_limit=profile.age_limit)
            if profile not in request.user.profiles.all():
                return redirect('netflixapp:profile-list')

            context = {
            'movies':movies
            }

            return render(request, 'movielist.html', context)
        except Profile.DoesNotExist:
            return redirect('netflixapp:profile-list')

method_decorator(login_required, name='dispatch')
class MovieDetail(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:
            movie = Movie.objects.get(uuid=movie_id)
            
            context = {
                'movie':movie
            }

            return render(request, 'moviedetail.html', context)
        except Movie.DoesNotExist:
            return redirect('netflixapp:profile-list')

method_decorator(login_required, name='dispatch')
class PlayMovie(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:
            movie = Movie.objects.get(uuid=movie_id)
            movie = movie.video.values()
            
            context = {
                'movie':list(movie)
            }

            return render(request, 'playmovie.html', context)
        except Movie.DoesNotExist:
            return redirect('netflixapp:profile-list')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'assets\favicon.png' %}" type="image/x-icon">
    <title>Netflix</title>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
</head>
<body class="bg-black text-gray-100">
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'assets/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>

        <div>
            {% if request.user.is_authenticated %}
            <a href="{% url 'account_logout' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                Logout
            </a>
            {% else %}
            <a href="{% url 'account_login' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                Sign In 
            </a>
            {% endif %}
        </div>
    </nav>
    {% block content %}

    {% endblock content %}
    <!-- <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">
            
            <li>&copy; All Right Reserved | 2022</li>
            <li> Netflix Clone</li>
            <li>By: Destiny Franks - Desphixs</li>
        </ul>
    </footer> -->
</body>
</html>

templates/index.html
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/391827d54c.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="{% static 'image\favicon.png' %}" type="image/x-icon">
     <title>Netflix India - Watch TV Shows Online, Watch Movies Online</title>
<style>
    
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
}

body {
    background-color: #000;
    color: #fff;
}

.imgdiv
{
    width: 100%;
    height: 100vh;
    background-image:url("{% static 'assets\background.jpg'%}");
    background-size: cover;
    background-position: center;
    padding: 10px 8%;
    position: relative;

}
nav {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px 0;
}

.logo {
    width: 150px;
    cursor: pointer;
}

nav button {
    border: none;
    outline: none;
    background-color: #db0001;
    color: #fff;
    padding: 7px 20px;
    font-size: 12px;
    border-radius: 4px;
    margin-left: 10px;
    cursor: pointer;
}

.lang-btn {
    display: inline-flex;
    align-items: center;
    background: transparent;
    border: 1px solid #fff;
    padding: 7px 10px;
}

.lang-btn img {
    width: 10px;
    margin-left: 10px;
} 

.fa-globe {
    color: #fff;
    width: 10px;
    margin-right: 10px;
}

.header-content {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
    text-align: center;
    margin-top: 100px;
}

.header-content h1 {
    font-size: 60px;
    line-height: 70px;
    font-weight: 600;
    max-width: 650px;
}

.header-content h3 {
    font-weight: 400;
    margin-bottom: 20px;
}

.email-signup {
    background: #fff;
    border-radius: 4px;
    display: flex;
    align-items: center;
    margin-top: 30px;
    overflow: hidden;
}

.email-signup input {
    flex: 1;
    border: 0;
    outline: 0;
    margin-left: 20px;
}

.email-signup button {
    background-color: #db0001;
    border: none;
    outline: none;
    color: #fff;
    font-size: 16px;
    cursor: pointer;
    padding: 15px 30px;
}


.features {
    padding: 50px 12%;
    font-size: 22px;
}

.row {
    display: flex;
    align-items: center;
    width: 100%;
    flex-wrap: wrap;
    padding: 50px 0;
}

.text-col, .img-col {
    flex-basis: 50%;
    margin-bottom: 20px;
}

.img-col img {
    display: block;
    width: 90%;
    margin: auto;
}

.features h2 {
    font-size: 50px;
    font-weight: 600;
    margin-bottom: 20px;
}

.faq {
    padding: 10px 12%;
    text-align: center;
    font-size: 18px;
}

.faq h2 {
    font-size: 40px;
    font-weight: 500;
}

.accordion {
    margin: 60px auto;
    width: 100%;
    max-width: 750px;
}

.accordion li {
    list-style: none;
    width: 100%;
    padding: 5px;
}

.accordion li label {
    display: flex;
    align-items: center;
    padding: 20px;
    font-size: 18px;
    font-weight: 500;
    background-color: #303030;
    margin-bottom: 2px;
    cursor: pointer;
    position: relative;
}

label::after {
    content: '+';
    font-size: 34px;
    position: absolute;
    right: 20px;
    transition: transform 0.5s;
}

input[type="radio"] {
    display: none;
}

.accordion .content {
    background-color: #303030;
    text-align: left;
    padding: 0 20px;
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.5s, padding 0.5s;
}

.accordion input[type="radio"]:checked + label + .content {
    max-height: 600px;
    padding: 30px 20px;
}

.accordion input[type="radio"]:checked + label::after {
    transform: rotate(135deg);
}

.faq small {
    font-size: 13px;
}

.faq .email-signup {
    max-width: 600px;
    margin: 20px auto 60px;
}


.footer {
    padding: 50px 15% 10px;
    border-top: 6px solid #333;
    color: #777;
}

.footer h2 {
    font-size: 18px;
    font-weight: 400;
    margin-bottom: 30px;
}

.footer .col {
    flex-basis: 25%;
    flex-grow: 1;
    margin-bottom: 20px;
}

.footer .col a {
    display: block;
    color: #777;
    font-size: 14px;
    margin-bottom: 10px;
    text-decoration: none;
}

.footer .row {
    align-items: flex-start;
    padding: 10px 0px;
}

.footer .lang-btn {
    color: #fff;
    padding: 10px 20px;
    border-radius: 3px;
}

.copyright-text {
    font-size: 14px;
    margin-top: 20px;
    margin-bottom: 10px;
}



@media only screen and (max-width: 600px) {
    .logo {
        width: 100px;
    }

    nav button {
        padding: 5px 10px;
    }

    nav .lang-btn {
        padding: 4px 8px;
    }

    .header-content {
        position: unset;
        transform: none;
        padding-top: 150px;
    }

    .header-content h1 {
        font-size: 30px;
    }

    .email-signup button {
        font-size: 12px;
        padding: 10px 15px;
    }

    .text-col, .img-col {
        flex-basis: 100%;
    }

    .features h2 {
        font-size: 30px;
    }

    .features p {
        font-size: 15px;
    }

    .row:nth-child(2), .row:nth-child(4) {
        flex-direction: column-reverse;
    }

    .features .row {
        padding: 10px 0;
    }

    .faq h2 {
        font-size: 20px;
    }

    .accordion .content {
        font-size: 14px;
    }

    .accordion li label {
        padding: 10px;
        font-size: 14px;
    }

    label::after {
        font-size: 22px;
    }
}
</style>
</head>
<body>
    <div class="header">
<div class="imgdiv">
        <nav>
            <img class="logo" src="{%static 'assets\logo.png'%}" alt="logo">
            <div>
                <button class="lang-btn"><i class="fa-solid fa-globe"></i> English <img src="{%static 'assets\down-icon.png'%}"></button>
                <button ><a href="{% url 'account_login' %}">sign in</a></button>
            </div>
        </nav>

        <div class="header-content">
            <h1>Unlimited movies, TV shows and more.</h1>
            <h3>Watch anywhere. Cancel anytime.</h3>
            <p>Ready to watch? Enter your email to create or restart your membership.</p>
            <form action="#" class="email-signup">
                <input type="email" placeholder="Email address" required>
                <button type="submit"><a href="{% url 'account_login' %}">Get Started</a></button>
            </form>
        </div>
</div>
    </div>

    <div class="features">
        <div class="row">
            <div class="text-col">
                <h2>Enjoy on your TV.</h2>
                <p>Watch on smart TVs, PlayStation, Xbox, Chromecast, Apple TV, Blu-ray players and more.</p>
            </div>
            <div class="img-col">
                <img src="{%static 'assets\feature-1.png'%}" alt="feature-1">
            </div>
        </div>
        <div class="row">
            <div class="img-col">
                <img src="{%static 'assets\feature-2.png'%}" alt="feature-2">
            </div>
            <div class="text-col">
                <h2>Download your shows to watch offline.</h2>
                <p>Save your favourites easily and always have something to watch.</p>
            </div>
        </div>
        <div class="row">
            <div class="text-col">
                <h2>Watch everywhere.</h2>
                <p>Stream unlimited movies and TV shows on your phone, tablet, laptop, and TV.</p>
            </div>
            <div class="img-col">
                <img src="{%static 'assets\feature-3.png'%}" alt="feature-3">
            </div>
        </div>
        <div class="row">
            <div class="img-col">
                <img src="{%static 'assets\feature-4.png'%}" alt="feature-4">
            </div>
            <div class="text-col">
                <h2>Create profiles for children.</h2>
                <p>Send children on adventures with their favourite characters in a space made just for them—free with your membership.</p>
            </div>
        </div>
    </div>


  
    <div class="faq">
        <h2>Frequently Asked Questions</h2>

        <ul class="accordion">
            <li>
                <input type="radio" name="accordion" id="first">
                <label for="first">What is Netflix?</label>
                <div class="content">
                    <p>Netflix is a streaming service that offers a wide variety of award-winning TV shows, movies, anime, documentaries and more – on thousands of internet-connected devices.<br><br>
                    You can watch as much as you want, whenever you want, without a single ad – all for one low monthly price. There's always something new to discover, and new TV shows and movies are added every week!</p>
                </div>
            </li>
            <li>
                <input type="radio" name="accordion" id="second">
                <label for="second">How much does Netflix cost?</label>
                <div class="content">
                    <p>Watch Netflix on your smartphone, tablet, Smart TV, laptop, or streaming device, all for one fixed monthly fee. Plans range from ₹ 149 to ₹ 649 a month. No extra costs, no contracts.</p>
                </div>
            </li>
            <li>
                <input type="radio" name="accordion" id="third">
                <label for="third">Where can I watch?</label>
                <div class="content">
                    <p>Watch anywhere, anytime. Sign in with your Netflix account to watch instantly on the web at netflix.com from your personal computer or on any internet-connected device that offers the Netflix app, including smart TVs, smartphones, tablets, streaming media players and game consoles.<br><br>
                    You can also download your favourite shows with the iOS, Android, or Windows 10 app. Use downloads to watch while you're on the go and without an internet connection. Take Netflix with you anywhere.</p>
                </div>
            </li>
            <li>
                <input type="radio" name="accordion" id="fourth">
                <label for="fourth">How do I cancel?</label>
                <div class="content">
                    <p>Netflix is flexible. There are no annoying contracts and no commitments. You can easily cancel your account online in two clicks. There are no cancellation fees – start or stop your account anytime.</p>
                </div>
            </li>
            <li>
                <input type="radio" name="accordion" id="fifth">
                <label for="fifth">What can I watch on Netflix?</label>
                <div class="content">
                    <p>Netflix has an extensive library of feature films, documentaries, TV shows, anime, award-winning Netflix originals, and more. Watch as much as you want, anytime you want.</p>
                </div>
            </li>
            <li>
                <input type="radio" name="accordion" id="sixth">
                <label for="sixth">Is Netflix good for Kids?</label>
                <div class="content">
                    <p>The Netflix Kids experience is included in your membership to give parents control while kids enjoy family-friendly TV shows and films in their own space.<br><br>
                    Kids profiles come with PIN-protected parental controls that let you restrict the maturity rating of content kids can watch and block specific titles you don’t want kids to see.</p>
                </div>
            </li>
        </ul>
        
        <small>Ready to watch? Enter your email to create or restart your membership.
        </small>
        
        <form action="#" class="email-signup">
            <input type="email" placeholder="Email address" required>
            <button type="submit">Get Started</button>
        </form>  
    </div>

    <div class="footer">
        <h2>Questions? Call 6352886034,9265578609</h2>

        <div class="row">
            <div class="col">
                <a href="#">FAQ</a>
                <a href="#">Investor Relations</a>
                <a href="#">Privacy</a>
                <a href="#">Speed Test</a>
            </div>
            <div class="col">
                <a href="#">Help Centre</a>
                <a href="#">Jobs</a>
                <a href="#">Cookie Preferences</a>
                <a href="#">Legal Notices</a>
            </div>
            <div class="col">
                <a href="#">Account</a>
                <a href="#">Ways to Watch</a>
                <a href="#">Corporate Information</a>
                <a href="#">Only on Netflix</a>
            </div>
            <div class="col">
                <a href="#">Media Centre</a>
                <a href="#">Terms of Use</a>
                <a href="#">Contact Us</a>
            </div>
        </div>

        <button class="lang-btn"><i class="fa-solid fa-globe"></i> English <img src="{%static 'assets\down-icon.png'%}"></button>

        <p class="copyright-text">Netflix India</p>
    </div>

</body>
</html>

templates/moviedetail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class='bg-primary_black min-h-screen h-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-right items-end bg-cover" style="background-image: url('{{ movie.image.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4" style="font-weight: bolder;">
                    {{ movie.title }}
                </h2>
                <p class=" w-11/120 md:w-5/12 font-medium text-white my-4">
                    {{movie.description}}
                </p>
                <div class="flex my-4">

                    <a href="{% url 'netflixapp:play-movie' movie_id=movie.uuid %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>                      
                     <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                     </a>
    
                    
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-100'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-3xl font-medium">
                    Description
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">
                        {{movie.description}}
                    </p>
                </div>
            </div>
        </section>
        
    </main>
    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            
            if(scrollY>200){
                nav.classList.add('bg-gray-900')
          
            }else{
                nav.classList.remove('bg-gray-900')
                
            }
        })

    </script>

{% endblock content %}

templates/playmovie.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <main class='bg-primary_black h-full w-full '>
        {{movie|json_script:'movie_data'}}
        <video  controls class="w-full h-screen player"></video>
        
    </main>
    <script>
        const videoEl = document.querySelector('video')
        const movie_data = JSON.parse(document.getElementById('movie_data').textContent);
        const url = new URL(location.href)
        const video_param = parseInt(url.searchParams.get('epi'))?parseInt(url.searchParams.get('epi')):0
        videoEl.setAttribute('src', `http://localhost:8000/media/${movie_data[video_param].file}`)
    </script>
{% endblock content %}

templates/profilecreate.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class='bg-primary_black min-h-screen py-20 md:py-32 flex-col flex items-center' style="background-image: url('assets/background_netflix.jpg');">
        <div class="flex flex-wrap justify-center  w-10/12  md:w-6/12">
            <form class="w-full md:w-8/12 bg-gray-900 p-5 rounded-lg" method="POST">{% csrf_token %}
                <h1 class="text-4xl text-center text-gray-100 font-medium">
                    Create A Profile
                </h1>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Profile Name
                    </Label>
                    <input required class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full" type="text" name="name" id="id_name" placeholder="Profile name">
                </div>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Maturity Level
                    </Label>
                    <select class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"  name="age_limit" id="id_age_limit" >
                        <option value="All">All</option>
                        <option value="Kids">Kids</option>
                       
                    </select>
                </div>
                <div class="flex justify-center items-center">
                    <button class="px-4 py-2 rounded-md outline-none bg-primary_red text-gray-100" type="submit">Create Profile</button>
                </div>
            </form> 
        </div>
        
    </section>
    {% endblock content %}

templates/profilelist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class='bg-primary_black min-h-screen py-20 md:py-0 flex-col flex justify-center items-center' style="background-image: url('assets/background_netflix.jpg');">
        <h2 class="text-center font-medium text-5xl my-4 text-gray-100">
            Who's watching ?
        </h2>

        <div class="flex flex-wrap justify-center items-center w-10/12  md:w-6/12">
            {% for profile in profiles %}
            <a href="{% url 'netflixapp:movie-list' profile_id=profile.uuid %}">
                <div class="w-32 h-32 m-4  bg-blue-500 rounded-md cursor-pointer justify-center items-center flex-col flex">
                    <p class="text-6xl" style="font-weight: 900;">{{ profile.name|slice:":1" }}</p>
                    <p>{{ profile.name }}</p>
                </div>
            </a>
            {% endfor %}
            
        </div>
        <div class="flex justify-center items-center">
            <a href="{% url 'netflixapp:profile-create' %}" class="px-4 py-2 rounded-md outline-none bg-gray-400 text-gray-100">
                Add A New Profile
            </a>
        </div>
    </section>

{% endblock content %}